### ISSUE TITLE
TrajectoryGeneration Class

### ISSUE THREAD

**Issue by echandler5956f** [echandler5956f/Galileo#20]
Do we actually need the TrajectoryGeneration class? If so, where does it fit in? Right now, targets can be specified via terminal cost (Phi), and state initial conditions are already handled in TrajectoryOpt.

**Comment by Akshay5312** [comment]
Probably not! We still need some sort of (extensible) "problem data" structure that contains information like the mode, ideal footstep trajectory, target and starting configuration to enable generic constraints.

It (preferably) shouldn't have to take a user a lot of effort to set up the problem data.

**Comment by echandler5956f** [comment]
Done!
