### ISSUE TITLE
Contact is not valid

### ISSUE THREAD

**Issue by echandler5956f** [echandler5956f/Galileo#25]
examples/model_building_test returns with

`terminate called after throwing an instance of 'std::runtime_error'
  what():  'Contact is not valid!'
Aborted`

There seems to be an issue somewhere in addPhase

**Comment by Akshay5312** [comment]
which addPhase? Is it when adding the initial phase?

**Comment by echandler5956f** [comment]
Now runs successfully (ChatGPT may have helped) with this output:

```c++
Built model
Set the end effectors
Set the robot
Set the ground
Set the states
Set the modes
Set the contact sequence
Finished setting up the problem
phase 0 time -- 1
phase 0 contacts --
phase 1 time -- 1
phase 1 contacts --
phase 2 time -- 1
phase 2 contacts --
```
